version: '1'
services:
  front:
    image: pixelback-front
    container_name: front
    restart: unless-stopped
    links:
      - bot
    depends_on:
      - bot
    ports:
      - 8080:80
  
  bot:
    image: pixelback-bot
    container_name: bot
    restart: unless-stopped
    links: 
      - backend
    depends_on:
      - backend
    environment:
      DB_HOST: postgres
      DATABASE: root
      DB_USER: root
      DB_PORT: 5432
      DB_PASSWORD: root
  
  update:
    image: pixelback-currency
    container_name: update-currency
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DATABASE: root
      DB_USER: root
      DB_PORT: 5432
      DB_PASSWORD: root
      API_URL: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest
      API_KEY: 26bce908-6591-4261-9637-720727e129a8
      UPDATE_RATE: 3600
      UPDATE_BETWEEN_RATE: 20
      PYTHONUNBUFFERED: False
    links:
      - postgres
    depends_on:
      - postgres
  
  backend:
    image: pixelback-backend
    container_name: backend
    restart: unless-stopped
    ports:
    - 5000:5000
    environment:
      DEBUG: false
      HOST: 0.0.0.0
      PORT: 5000
      DB_HOST: postgres
      DATABASE: root
      DB_USER: root
      DB_PORT: 5432
      DB_PASSWORD: root
    volumes:
      - appdata:/var/www
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
    - '7000:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/db
    volumes:
      - postgresdata:/data/db

volumes:
  postgresdata:
    driver: local
  appdata:
    driver: local
